parameters:

services:
  netdudes_importer.event_dispatcher:
    class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
    arguments:
        - '@service_container'

  netdudes_importer.yaml_parser_factory:
    class: Netdudes\ImporterBundle\Yaml\YamlParserFactory

  netdudes_importer.yaml_parser:
    class: Symfony\Component\Yaml\Parser
    factory:
        - "@netdudes_importer.yaml_parser_factory"
        - create

  netdudes_importer.configuration_reader.yaml:
    class: Netdudes\ImporterBundle\Importer\Configuration\Reader\YamlConfigurationReader
    arguments:
        - "@netdudes_importer.yaml_parser"
        - "@netdudes_importer.configuration.factory"

  netdudes_importer.configuration.factory:
    class: Netdudes\ImporterBundle\Importer\Configuration\Field\FieldConfigurationFactory

  netdudes_importer.csv_parser:
    class: Netdudes\ImporterBundle\Importer\Parser\CsvParser

  netdudes_importer.interpreter.entity_data_factory:
    class: Netdudes\ImporterBundle\Importer\Interpreter\EntityDataInterpreterFactory
    arguments:
        - "@doctrine.orm.entity_manager"
        - "@validator"
        - '@netdudes_importer.event_dispatcher'

  netdudes_importer.interpreter.updating_entity_data_factory:
      class: Netdudes\ImporterBundle\Importer\Interpreter\UpdatingEntityDataInterpreterFactory
      arguments:
        - "@doctrine.orm.entity_manager"
        - "@validator"
        - '@netdudes_importer.event_dispatcher'

  netdudes_importer.interpreter.relationship_data_factory:
    class: Netdudes\ImporterBundle\Importer\Interpreter\RelationshipDataInterpreterFactory
    arguments:
        - "@doctrine.orm.entity_manager"

  netdudes_importer.interpreter.data_factory:
    class: Netdudes\ImporterBundle\Importer\Interpreter\DataInterpreterFactory
    arguments:
      - "@netdudes_importer.interpreter.entity_data_factory"
      - "@netdudes_importer.interpreter.updating_entity_data_factory"
      - "@netdudes_importer.interpreter.relationship_data_factory"

  netdudes_importer.csv_importer_factory:
    class: Netdudes\ImporterBundle\Importer\CsvImporterFactory
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@netdudes_importer.csv_parser"
      - "@netdudes_importer.interpreter.data_factory"

  netdudes_importer.multiple_file_csv_import_manager_factory:
    class: Netdudes\ImporterBundle\Importer\MultipleFileCsvImportManagerFactory
    arguments:
        - "@netdudes_importer.csv_importer_factory"

  netdudes_importer.multiple_file_csv_import_manager:
    class: Netdudes\ImporterBundle\Importer\MultipleFileCsvImportManager
    factory:
        - "@netdudes_importer.multiple_file_csv_import_manager_factory"
        - create

  netdudes_importer.legacy_fixtures_wrapper:
    class: Netdudes\ImporterBundle\Importer\LegacyFixturesImporterWrapper
    arguments:
        - "@netdudes_importer.csv_importer_factory"
        - "@netdudes_importer.configuration_reader.yaml"
